[2024-06-28T14:38:45.867+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T14:38:45.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transfer_to_gcs.upload_to_gcs manual__2024-06-28T14:38:43.451877+00:00 [queued]>
[2024-06-28T14:38:45.893+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transfer_to_gcs.upload_to_gcs manual__2024-06-28T14:38:43.451877+00:00 [queued]>
[2024-06-28T14:38:45.894+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T14:38:45.906+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_to_gcs> on 2024-06-28 14:38:43.451877+00:00
[2024-06-28T14:38:45.916+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_transfer_to_gcs', 'upload_to_gcs', 'manual__2024-06-28T14:38:43.451877+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/to_gcs.py', '--cfg-path', '/tmp/tmp2u2jfn1h']
[2024-06-28T14:38:45.918+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask upload_to_gcs
[2024-06-28T14:38:45.919+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=561) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-28T14:38:45.919+0000] {standard_task_runner.py:63} INFO - Started process 563 to run task
[2024-06-28T14:38:45.960+0000] {task_command.py:426} INFO - Running <TaskInstance: data_transfer_to_gcs.upload_to_gcs manual__2024-06-28T14:38:43.451877+00:00 [running]> on host 25c2a2aa63fd
[2024-06-28T14:38:46.079+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_transfer_to_gcs' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T14:38:43.451877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T14:38:43.451877+00:00'
[2024-06-28T14:38:46.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T14:38:46.112+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-28T14:38:46.119+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-28T14:38:46.119+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T14:38:46.120+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 98, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: None
[2024-06-28T14:38:46.129+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_transfer_to_gcs, task_id=upload_to_gcs, run_id=manual__2024-06-28T14:38:43.451877+00:00, execution_date=20240628T143843, start_date=20240628T143845, end_date=20240628T143846
[2024-06-28T14:38:46.145+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 146 for task upload_to_gcs (None; 563)
[2024-06-28T14:38:46.172+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T14:38:46.202+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T14:38:46.204+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
